### ISSUE TITLE
Demo doesn't run

### ISSUE THREAD

**Issue by deaton1337** [esdg/GodotSceneManager#52]
Hi,
Your demo doesn't run on my machine, there's a hard code path in `\GodotSceneManager\addons\ScenesManager\Settings\SceneManagerSettings.tres` that I had to change.

```[gd_resource type="Resource" load_steps=2 format=3 uid="uid://s2qas5voe4ff"]

[ext_resource type="Script" path="res://addons/ScenesManager/Scripts/Resources/SceneManagerSettings.cs" id="1_bv3om"]

[resource]
script = ExtResource("1_bv3om")
SceneManagerSchemaPath = "D:/Development/GodotSceneManager/Demo/SceneManagerSchemas/DemoGraph.tres"
```

**Comment by esdg** [comment]
The file dialog is set on file system, using paths like "c:/my/path", it need to be changed to "res:/' so it will be correctly referenced in any computers.

Changed from `FileDialog.Access = FileDialog.AccessEnum.Filesystem` to `FileDialog.Access = FileDialog.AccessEnum.Resources`
